"""empty message

Revision ID: 7190818b46e8
Revises: 36300b17550e
Create Date: 2024-05-13 11:24:34.711048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7190818b46e8'
down_revision = '36300b17550e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reptiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('common_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('scientific_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('conservation_status', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('native_habitat', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('fun_fact', sa.Text(), nullable=True))
        batch_op.drop_column('info')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reptiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('info', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('fun_fact')
        batch_op.drop_column('native_habitat')
        batch_op.drop_column('conservation_status')
        batch_op.drop_column('scientific_name')
        batch_op.drop_column('common_name')

    # ### end Alembic commands ###
